version: 2 # use CircleCI 2.0

defaults: &defaults
  environment:
    # Configure the JVM and Gradle to avoid OOM errors
    _JAVA_OPTIONS: "-Xmx3g"
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"

  docker: # run the steps with Docker
    - image: circleci/openjdk:8u222-stretch # ...with this image as the primary container; this is where all `steps` will run

references:
  ## cache
  cache_paths: &cache_paths
    paths:
      - ~/work/.gradle
      - ~/.gradle

  cache_tests_key: &cache_tests_key
    key: test-deps-{{ checksum "build.gradle" }}-{{ checksum "build.gradle" }}

  restore_tests_cache: &restore_tests_cache
    restore_cache:
      <<: *cache_tests_key

  save_tests_cache: &save_tests_cache
    save_cache:
      <<: *cache_tests_key
      <<: *cache_paths

jobs: # a collection of steps
  build:
    <<: *defaults
    steps: # a collection of executable commands
      - checkout # check out source code to working directory
      - *restore_tests_cache
      - run:
          name: Run tests
          command:
            gradle test --tests "samantha.tests.AppTest"
      - *save_tests_cache
      - store_test_results:
          # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: build/test-results/test
      - store_artifacts: # Upload test results for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: build/test-results/test
          when: always

workflows:
  version: 2
  workflow:
    jobs:
      - build