/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package samantha.tests;

import org.junit.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.equalTo;
import static org.junit.Assert.*;
import io.restassured.RestAssured.*;
import io.restassured.matcher.RestAssuredMatchers.*;
import org.hamcrest.Matchers.*;
import io.restassured.module.jsv.JsonSchemaValidator.*;

public class AppTest {

    @Test
    public void testShouldResponseBeOk() {

        given()
        .when()
                .get("https://jsonplaceholder.typicode.com/users/3")
        .then()
                .assertThat()
                .body("email", equalTo("Nathan@yesenia.net"));
    }
}
